site_name: MyDocs for cyberalong
theme:
  favicon: aerlingus-color.png
  icon: 
      logo: simple/aerlingus
      
      
  name: material
  custom_dir: overrides

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - toc.integrate
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  font: false 
  language: zh
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo 
      accent: blue
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo
      accent: lime

#代码高亮
markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: On this Page
      toc_depth: 4  
      permalink_title: Anchor link to this section for reference
  # - meta
  - def_list
  - attr_list
  - md_in_html
  # - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dragonzhoulong
    # - icon: fontawesome/brands/zhihu
    #   link: 

extra_css:
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/utils/katex.min.css
  - css/custom.css
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - js/tablesort.js
  - https://cdn.tonycrane.cc/utils/katex.min.js
  - js/katex.js

copyright: |
  &copy; 2023<a href="https://github.com/dragonzhoulong" target="_blank" rel="noopener"> dragon</a>
plugins:
  - table-reader
  - search
  
  
nav:
  - Home:
    - index.md
    - buidling: page1.md
  - CSAPP:
    - csapp/index.md
    - bomblab: csapp/csapp.md

  - PA:
    - PA/index.md
    - PA: PA/PA.md
    - riscv: PA/riscv.md
  - tool:
    - tool/index.md
    - git: tool/git.md
  - leetcode:
    - leetcode/index.md
    - 基础算法: leetcode/base.md