site_name: MyDocs for cyberalong
theme:
  
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  font: false 
  language: zh
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

#代码高亮
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      # line_spans: __span
      # pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark:
      smart_mark: true
  - attr_list
  - pymdownx.superfences
#博客
# plugins:
#   - blog
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dragonzhoulong
    # - icon: fontawesome/brands/zhihu
    #   link: 

extra_css:
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css

copyright: |
  &copy; 2023<a href="https://github.com/dragonzhoulong" target="_blank" rel="noopener"> dragon</a>
   